service: serverless

provider:
  name: aws
  runtime: nodejs10.x
  stage: beta
  region: sa-east-1
  memorySize: 128

functions:
  estados:
    handler: estados.getEstados
    events:
      - http:
          path: estados
          method: get
          cors: true
  cidades:
    handler: cidades.getCidades
    events:
      - http:
          path: cidades/{sigla}
          method: get
          cors: true